### ISSUE TITLE
Expose OpenTelemetry SDK configuration in MP Config

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentelemetry#12]
We should decide what SKD components will be mandatory what which optional. For example some vendors might support exporters to different telemetry systems (StackDriver, Zipkin).

By default, we should aim to use only exporter for OpenTelemetry format and necessary sampling configuration.

**Comment by svenhaag** [comment]
yet another new format? who will support this and when?
i think this will inhibit adaption as people already may have a specific system/server.
do i miss something?

**Comment by pavolloffay** [comment]
I am not sure if I understand you @svenhaag. What do you mean by new format?

OpenTelemetry provides an API and SDK(implementation). It is expected that there will be only one implementation of the API - this is the major difference to OpenTracing. Hence we would like to use the SDK directly in the MicroProfile. 

The SDK supports various components - samplers, exporters etc. We should decide what components will be managed by MP-OTEL. I would advocate for a bare minimum - all samplers and exporter in OTEL proto format. MP vendors could of course support exporters to other systems or additional components of the SDK.

**Comment by radcortez** [comment]
Implemented in https://github.com/smallrye/smallrye-opentelemetry/commit/8e0034b5c35575e533e27f88b6c8b3ea60de6f63
