### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentelemetry#13]
@kenfinnigan could you please take this one? It seems I don't have permissions to add new projects to semaphore.

**Comment by kenfinnigan** [comment]
@pavolloffay we're actually moving away from Semaphore to GH Actions.

You can take a look at what SmallRye Config has done, and @radcortez should be able to answer any questions

**Comment by radcortez** [comment]
Hi @pavolloffay, please have a look into https://github.com/smallrye/smallrye-parent/wiki/SmallRye-Release-Process.

If you don't feel comfortable, I can submit the PR here to activate GH Actions.

**Comment by pavolloffay** [comment]
It's great to see going away from the semaphoreci! 

I can configure the GH actions, we are using it in other projects. At the beginning, we just need to run the test target. The full release support can come later. 

Are the GH actions enabled for this repository? 

Any objections on using a maven wrapper?

**Comment by radcortez** [comment]
Hey @pavolloffay, GH Actions turn on automatically, once you have a .github/workflow file.

Since we only have build, I recommend to just use the build file here:
https://github.com/smallrye/smallrye-jwt/blob/5807929f3a9e80736b6d7836e79fc2fcd739d92f/.github/workflows/build.yml
