### ISSUE TITLE
Server side JAX-RS tracing

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentelemetry#2]
* Provide an auto-instrumentation for server-side JAX-RS
* The instrumentation should use OpenTelemetry API artifact

SmallRyeOpenTracing is using JAX-RS request filter to start spans and a servlet filter to finish spans. The servlet filter is necessary to catch exceptions and finish spans exceptions.

OpenTracing implementation lives here https://github.com/opentracing-contrib/java-jaxrs/tree/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/server

**Comment by pavolloffay** [comment]
We could simply for the instrumentation with tests to OpenTelemetry initially in this repository as a Maven submodule.

**Comment by kenfinnigan** [comment]
Is this needed going forward?

Why not use https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/instrumentation/jaxrs ?

**Comment by pavolloffay** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation uses Javaagent as instrumentation technology.  

In MicroProfile we are aiming to provide white box instrumentation dependency with a programmatic API.

**Comment by kenfinnigan** [comment]
Do you mean in creating an MP API, or just defining in the spec that an implementation should use a programmatic API from OpenTelemetry to propagate spans?

**Comment by pavolloffay** [comment]
Just defining in the spec that an implementation should use OpenTelemetry API. However in MP-OpenTracing we have learned that it's better to minimize exposure of the 3rd party APIs, especially when they introduce breaking changes. Hence we should build on this principle.

OpenTelemetry APIs promises to be more stable than OpenTracing, which is a good thing for us.
