### ISSUE TITLE
http.route is not built correctly

### ISSUE THREAD

**Issue by Spindl** [smallrye/smallrye-opentelemetry#242]
Over the course of trying to upgrade to the latest WildFly version (28.0.1.Final at the time), we noticed that the name of our traces looked kind of weird in our visualization.
We investigated and found that the `http.route` tag (which is also used as the name of a span coincidentally) is not built correctly.
It should be `<context-root>/<resource>/<method>`, but actually is `<resource>/<context-root>/<method>`

Here is an example: 
* Our context-root is `gemini-web/rest`
* Our resource `core-test/core-tests` 
* Our method has the path parameter `{id}`:

The route should be: `/gemini-web/rest/core-test/core-tests/{id: [0-9]*}`
But it actually is: `/core-test/core-tests/gemini-web/rest/{id: [0-9]*}`

![image](https://github.com/smallrye/smallrye-opentelemetry/assets/36992460/18d5c5b3-5b57-427e-be77-87c66b839f50)

It seems that the route is not determined correctly here: https://github.com/smallrye/smallrye-opentelemetry/blob/2.3.2/implementation/rest/src/main/java/io/smallrye/opentelemetry/implementation/rest/OpenTelemetryServerFilter.java#L176

WildFly uses version 2.3.2 of smallrye-opentelemetry, but judging from the code this is also awry in the master.

**Comment by radcortez** [comment]
@jasondlee let me know how do you want to handle this for WF.

**Comment by jasondlee** [comment]
@radcortez We just released WildFly 29, so WF 30 is the earliest we can ship the update, so there's probably no rush on a cutting a release of this. If you want, then, to sit on this change for a bit to make sure there are no other changes, that's fine with me. If, however, you'd like to cut the release so you don't have to keep track, that's also fine. Component updates on WF are pretty quick and easy.

**Comment by radcortez** [comment]
I can do a patch release of 2.3.x. I guess you can't update to 2.4.x due to the new OTel version, right?

**Comment by Thomas-WB** [comment]
@jasondlee Are there any upgrade plans for WildFly 30? The 30.0.0.Beta1 version still uses 2.3.2.

Otherwise a patch release 2.3.x would be great so that I can patch WildFly by my own.
