### ISSUE TITLE
Client side JAX-RS tracing

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentelemetry#3]
* Provide an auto-instrumentation for JAX-RS client.
* The instrumentation should use OpenTelemetry API artifact

OpenTracing implementation is here https://github.com/opentracing-contrib/java-jaxrs/tree/master/opentracing-jaxrs2/src/main/java/io/opentracing/contrib/jaxrs2/client

**Comment by fmhwong** [comment]
I can work on this one.

**Comment by radcortez** [comment]
Implemented in https://github.com/smallrye/smallrye-opentelemetry/commit/4b332de3063558f3317fe7b2ed1e9c5faca1d2cd.
