### ISSUE TITLE
`JvmGarbageCollectionTest` test not consistent

### ISSUE THREAD

**Issue by brunobat** [smallrye/smallrye-opentelemetry#343]
During the implementation [MP Telemetry 2.0 modifications for `smallrye-opentelemetry`](https://github.com/smallrye/smallrye-opentelemetry/pull/339) @radcortez found that `JvmGarbageCollectionTest` does not execute in a consistent way because the garbage collector might not have been executed during the duration of the test. 
Please check: https://github.com/smallrye/smallrye-opentelemetry/pull/339#issuecomment-2237230646

---

During the MP telemetry meeting from Jul. 22 it was decided that we would disable this test, for the time being and would rework the test to force a GC and wait for the data.

**Comment by brunobat** [comment]
cc @donbourne

**Comment by donbourne** [comment]
@brunobat , we've attempted to resolve it with https://github.com/eclipse/microprofile-telemetry/issues/225 .

**Comment by donbourne** [comment]
btw, I realize we agreed to comment out the test and fix it later - we had some pushback on our side about commenting out the test, so we looked at how we try to "guarantee" GC happens in other contexts and updated the test case.

**Comment by radcortez** [comment]
I tried with the latest snapshot, and it seems to work as expected. Thanks @donbourne
