### ISSUE TITLE
VertxGrpcSender lacks SSL support

### ISSUE THREAD

**Issue by dimitarp** [smallrye/smallrye-opentelemetry#396]
It is not possible with  smallrye-opentelemetry 2.8.x to export telemetry data to GRPC collectors requiring SSL connections. The newly added class VertxGrpcSender does not allow detailed configuration of the underlying GRPC client (see the [quarkus implementation](https://github.com/quarkusio/quarkus/blob/main/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/exporter/otlp/sender/VertxGrpcSender.java#L71) for comparison). Version 2.7.x uses the OkHttpGrpcSender which works with SSL.

**Comment by radcortez** [comment]
//cc @jasondlee
