### ISSUE TITLE
MicroProfile RestClient tracing

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentelemetry#4]
* Provide auto instrumentation for MicroProfile REST client

nit: https://github.com/smallrye/smallrye-opentracing/blob/master/implementation/src/main/java/io/smallrye/opentracing/SmallRyeRestClientListener.java#L14

**Comment by radcortez** [comment]
Implemented in https://github.com/smallrye/smallrye-opentelemetry/commit/4b332de3063558f3317fe7b2ed1e9c5faca1d2cd
