### ISSUE TITLE
Update to OpenTelemetry 1.42.1 to track MicroProfile Telemetry 2.0.1

### ISSUE THREAD

**Issue by jasondlee** [smallrye/smallrye-opentelemetry#409]
More info can be found [here](https://github.com/eclipse/microprofile-telemetry/releases/tag/2.0.1) and [here](https://github.com/eclipse/microprofile-telemetry/compare/2.0...2.0.1#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R34).

**Comment by brunobat** [comment]
done
