### ISSUE TITLE
Expose tracer to the application

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentelemetry#7]
We should start thinking about how the tracer will be exposed to the application. 

In OpenTracing tracer could be injected as a CDI bean via `@Inject Tracer`. In OpenTelemetry the preferred way is to get a tracer from a static accessor `OpenTelemetry.getTracerFactory().get("instrumentation name");`.

**Comment by Ladicek** [comment]
IMHO being able to inject a tracer is nice. We could use a qualifier annotation to specify a tracer name, and perhaps use some default name if no qualifier is used.

**Comment by radcortez** [comment]
Implemented in https://github.com/smallrye/smallrye-opentelemetry/commit/320c8a4cabf98e585f9779916ee328e2cbf4cd43
