### ISSUE TITLE
@Traced annotation

### ISSUE THREAD

**Issue by pavolloffay** [smallrye/smallrye-opentelemetry#9]
Provide behavior for `@Traced` annotation. Note that the annotation might be defined directly in the OpenTelemetry project https://github.com/open-telemetry/opentelemetry-java/issues/813.

Some related issues:
* https://github.com/eclipse/microprofile-opentracing/issues/189
* https://github.com/eclipse/microprofile-opentracing/issues/188

**Comment by radcortez** [comment]
We support `@WithSpan` from OpenTelemetry API.
